portal_vendors/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :tr_rfq_submission_dtls
  resources :tr_rfqs
  resources :tr_rfq_submissions
  authenticated :ms_vendor do
    root to: 'inquiries#index', as: :authenticated_root
  end
  root to: redirect('/login')

  devise_for :ms_vendors, path: '', controllers: {
    registrations: 'ms_vendors/registrations', passwords: 'ms_vendors/passwords'
  }, path_names: { sign_in: :login, sign_up: :register, password: :reset, confirmation: :verification }

  namespace :api do
    resources :images, only: :show do
      member do
        get :check_path
        get :get
      end
    end
  end

  resources :vendors do
    member do
      patch :update_password
    end
  end
  resources :inquiries
  resources :products_and_services, only: [:index, :update] do    
    member do
      get :download_template
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

portal_vendors/app/models/tr_rfq_submission.rb
class TrRfqSubmission < ApplicationRecord
	has_many :tr_rfq_submission_dtls
	accepts_nested_attributes_for :tr_rfq_submission_dtls, reject_if: :all_blank, allow_destroy: true
end

portal_vendors/app/controllers/tr_rfq_submissions_controller.rb
class TrRfqSubmissionsController < ApplicationController
  before_action :set_tr_rfq_submission, only: [:show, :edit, :update, :destroy]

  # GET /tr_rfq_submissions
  # GET /tr_rfq_submissions.json
  def index
    @tr_rfq_submissions = TrRfqSubmission.all
  end

  # GET /tr_rfq_submissions/1
  # GET /tr_rfq_submissions/1.json
  def show
  end

  # GET /tr_rfq_submissions/new
  def new
    @tr_rfq_submission = TrRfqSubmission.new
    @tr_rfq_submission.tr_rfq_submission_dtls.build
    @tr_rfq = TrRfq.find(params[:format])
  end

  # GET /tr_rfq_submissions/1/edit
  def edit
  end

  # POST /tr_rfq_submissions
  # POST /tr_rfq_submissions.json
  def create
    @tr_rfq_submission = TrRfqSubmission.new(tr_rfq_submission_params)
    respond_to do |format|
      if @tr_rfq_submission.save

        format.html { redirect_to inquiries_path, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location:inquiries_path }
        TrRfq.find(@tr_rfq_submission.tr_rfq_id).update(status: 'Submitted');
      else
        format.html { render :new }
        format.json { render json: @tr_rfq_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tr_rfq_submissions/1
  # PATCH/PUT /tr_rfq_submissions/1.json
  def update
    respond_to do |format|
      if @tr_rfq_submission.update(tr_rfq_submission_params)
        format.html { redirect_to @tr_rfq_submission, notice: 'Tr rfq submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @tr_rfq_submission }
      else
        format.html { render :edit }
        format.json { render json: @tr_rfq_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tr_rfq_submissions/1
  # DELETE /tr_rfq_submissions/1.json
  def destroy
    @tr_rfq_submission.destroy
    respond_to do |format|
      format.html { redirect_to tr_rfq_submissions_url, notice: 'Tr rfq submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tr_rfq_submission
      @tr_rfq_submission = TrRfqSubmission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tr_rfq_submission_params
      # params.require(:tr_rfq_submission).permit(:bidding_types, :description, :need_by_date, :term_of_payment, :no_quotation, :incoterms, :note, :is_active, :created_by, :updated_by)
      params.require(:tr_rfq_submission).permit(:bidding_types, :description, :need_by_date, :term_of_payment, :no_quotation, :incoterms, :note, :is_active, :created_by, :updated_by,
                                                :tr_rfq_id, tr_rfq_submission_attributes: [:id, :price, :offered_qty, :_destroy])
    end
end

portal_vendors/app/helpers/tr_rfq_submissions_helper.rb
module TrRfqSubmissionsHelper
end

portal_vendors/app/views/tr_rfq_submissions/_form.html.erb
<%= form_with(model: tr_rfq_submission, local: true) do |form| %>
  <% if tr_rfq_submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tr_rfq_submission.errors.count, "error") %> prohibited this tr_rfq_submission from being saved:</h2>
      <ul>
      <% tr_rfq_submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-panel-third">
  <div class="form-horizontal">
    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :item_name %>
        </div>
        <div class='col-sm-9'>
          <%= form.text_field :item_name, value: @tr_rfq.item_name, class:'form-control', disabled:true %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :delivery_site %>
        </div>
        <div class='col-sm-9'>
          <%= form.text_field :delivery_site, value: @tr_rfq.delivery_site, class:'form-control', disabled:true %>
        </div>
      </div>
    </div>  
    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :note %>
        </div>
        <div class='col-sm-9'>
          <%= form.text_field :note, value: @tr_rfq.note, class:'form-control', disabled:true %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="form-panel-third">
  <div class="form-horizontal">
    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :bidding_types %>
        </div>
        <div class='col-sm-9'>
          <%= form.select :bidding_types, ['As Requested', 'Not as Requested'], {include_blank:'-Select type-'}, class:'form-control' %>
        </div>
      </div>
    </div>
      
     <div class="row">
       <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :description %>
        </div>
        <div class='col-sm-9'>
          <%= form.text_area :description, value: @tr_rfq.description, class:'form-control', disabled:true %>
        </div>
      </div>
     </div>
      

    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :need_by_date %>
        </div>
        <div class='col-sm-9'>
          <%= form.date_select :need_by_date, value: @tr_rfq.need_by_date, class:'form-control', disabled:true %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :term_of_payment %>
        </div>
        <div class='col-sm-9'>
          <%= form.number_field :term_of_payment, value: @tr_rfq.term_of_payment, class:'form-control', disabled:true %>
        </div>
      </div>
    </div>

    <%= form.fields_for :tr_rfq_submission_dtls do |dtl| %>
       <%= render 'tr_rfq_submission_dtls', f: dtl %>
    <% end -%>
    <br><br>
    <div class="col-sm-12">
      <%= link_to_add_association 'Add Proposition', form, :tr_rfq_submission_dtls, partial: 'tr_rfq_submission_dtls' %>
    </div>
    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :incoterms %>
        </div>
        <div class='col-sm-9'>    
          <%= form.select :incoterms, ['CIP', 'DAT'], {include_blank:'-Select terms-'}, class:'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class='form-group'>
        <div class='col-sm-3 control-label'>
          <%= form.label :note %>
        </div>
        <div class='col-sm-9'>
          <%= form.text_area :note, class:'form-control' %>
        </div>
      </div>
    </div>
      <%= form.hidden_field :created_by, value: current_ms_vendor.id %>
      <%= form.hidden_field :updated_by, value: current_ms_vendor.id %>
      <%= form.hidden_field :tr_rfq_id, value: @tr_rfq.id  %>

    <div class="row">
      <div class="col-sm-10"></div>
      <div class="col-sm-1">  
        <div class="actions">
          <%= form.submit 'Submit', class: 'btn btn-warning', data: { confirm: 'Are you sure?' }  %>
        </div>
      </div>
      <div class="col-sm-1">
        <%= link_to 'Cancel', tr_rfq_submissions_path, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }  %>
      </div>  
    </div>
  </div>
</div>

<% end %>

<script type="text/javascript">
  $('#tr_rfq_submission_bidding_types').on('change', function(){
    if($('#tr_rfq_submission_bidding_types').val() == 'Not as Requested')
    {
      $('#tr_rfq_submission_description').attr('disabled', false);
      $('#tr_rfq_submission_need_by_date_1i').attr('disabled', false);
      $('#tr_rfq_submission_need_by_date_2i').attr('disabled', false);
      $('#tr_rfq_submission_need_by_date_3i').attr('disabled', false);
      $('#tr_rfq_submission_term_of_payment').attr('disabled', false);
    }
  })


</script>

portal_vendors/app/views/tr_rfq_submissions/_tr_rfq_submission_dtls.html.erb
<div class="nested-fields">
<div class="row">
  <div class='form-group'>
    <div class='col-sm-3 control-label'>
     <%= f.label :offered_qty %>
    </div>
    <div class='col-sm-9'>
    	<%= f.number_field :offered_qty %>
    </div>
  </div>
</div>
<div class="row">
  <div class='form-group'>
    <div class='col-sm-3 control-label'>
     <%= f.label :price %>
    </div>
    <div class='col-sm-9'>
    	<%= f.number_field :price %>
    </div>
  </div>
</div>
<%= link_to_remove_association 'Remove field', f %>

</div>

portal_vendors/app/views/tr_rfq_submissions/edit.html.erb
<h1>Editing Tr Rfq Submission</h1>

<%= render 'form', tr_rfq_submission: @tr_rfq_submission %>

<%= link_to 'Show', @tr_rfq_submission %> |
<%= link_to 'Back', tr_rfq_submissions_path %>

portal_vendors/app/views/tr_rfq_submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tr Rfq Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Bidding types</th>
      <th>Description</th>
      <th>Need by date</th>
      <th>Term of payment</th>
      <th>No quotation</th>
      <th>Incoterms</th>
      <th>Note</th>
      <th>Is active</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tr_rfq_submissions.each do |tr_rfq_submission| %>
      <tr>
        <td><%= tr_rfq_submission.bidding_types %></td>
        <td><%= tr_rfq_submission.description %></td>
        <td><%= tr_rfq_submission.need_by_date %></td>
        <td><%= tr_rfq_submission.term_of_payment %></td>
        <td><%= tr_rfq_submission.no_quotation %></td>
        <td><%= tr_rfq_submission.incoterms %></td>
        <td><%= tr_rfq_submission.note %></td>
        <td><%= tr_rfq_submission.is_active %></td>
        <td><%= tr_rfq_submission.created_by %></td>
        <td><%= tr_rfq_submission.updated_by %></td>
        <td><%= link_to 'Show', tr_rfq_submission %></td>
        <td><%= link_to 'Edit', edit_tr_rfq_submission_path(tr_rfq_submission) %></td>
        <td><%= link_to 'Destroy', tr_rfq_submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tr Rfq Submission', new_tr_rfq_submission_path %>

portal_vendors/app/views/tr_rfq_submissions/new.html.erb
<div class="content content-container">

<h1>New Tr Rfq Submission</h1>
		
<%= render 'form', tr_rfq_submission: @tr_rfq_submission %>
		
</div>

portal_vendors/app/views/tr_rfq_submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bidding types:</strong>
  <%= @tr_rfq_submission.bidding_types %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tr_rfq_submission.description %>
</p>

<p>
  <strong>Need by date:</strong>
  <%= @tr_rfq_submission.need_by_date %>
</p>

<p>
  <strong>Term of payment:</strong>
  <%= @tr_rfq_submission.term_of_payment %>
</p>

<p>
  <strong>No quotation:</strong>
  <%= @tr_rfq_submission.no_quotation %>
</p>

<p>
  <strong>Incoterms:</strong>
  <%= @tr_rfq_submission.incoterms %>
</p>

<p>
  <strong>Note:</strong>
  <%= @tr_rfq_submission.note %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @tr_rfq_submission.is_active %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @tr_rfq_submission.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @tr_rfq_submission.updated_by %>
</p>

<%= link_to 'Edit', edit_tr_rfq_submission_path(@tr_rfq_submission) %> |
<%= link_to 'Back', tr_rfq_submissions_path %>