portal_vendors/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :tr_rfq_submission_dtls
  resources :tr_rfqs
  resources :tr_rfq_submissions
  authenticated :ms_vendor do
    root to: 'inquiries#index', as: :authenticated_root
  end
  root to: redirect('/login')

  devise_for :ms_vendors, path: '', controllers: {
    registrations: 'ms_vendors/registrations', passwords: 'ms_vendors/passwords'
  }, path_names: { sign_in: :login, sign_up: :register, password: :reset, confirmation: :verification }

  namespace :api do
    resources :images, only: :show do
      member do
        get :check_path
        get :get
      end
    end
  end

  resources :vendors do
    member do
      patch :update_password
    end
  end
  resources :inquiries
  resources :products_and_services, only: [:index, :update] do    
    member do
      get :download_template
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

portal_vendors/app/views/layouts/_header.html.erb
<header class='header white-bg'>
  <a href='/' class='logo'><%= image_tag('nutrifood-logo-small.png')%> <b>Portal Vendor</b></a>
  <div class='top-menu'>
    <% if ms_vendor_signed_in? %>
      <ul class='main-menu'>
        <li>
          <%= link_to 'Inquiries', inquiries_path, class:
        "#{'active' if params[:controller] == 'inquiries'}" %>
        </li>
        <li>
          <%= link_to 'Products & Services', products_and_services_path, class:
        "#{'active' if params[:controller] == 'products_and_services'}" %>
        </li>
        <li>
          <%= link_to 'Vendor Info', edit_vendor_path(current_ms_vendor), class:
        "#{'active' if params[:controller] == 'vendors'}" %>
        </li>
      </ul>
      <ul class='nav pull-right top-menu'>
        <!-- <li>
          <span class='float-left user-name'><strong>Welcome, <%#= link_to current_ms_vendor.vendor, edit_ms_vendor_registration_url, data: { turbolinks: false } %></strong></span>
        </li> -->
        <li>
          <span class='float-left user-name'><strong>Welcome, <%= current_ms_vendor.vendor %></strong></span>
        </li>
        <li>
          <%= link_to 'Logout', destroy_ms_vendor_session_url, method: :delete, class: 'logout btn btn-warning' %>
        </li>
      </ul>
    <% else %>
      <ul class='pull-right menu-login'>
        <li>
          <%= link_to 'Login', ms_vendor_session_path, class: 'login btn btn-warning' %>
        </li>
        <li>
          <%= link_to 'Register', new_registration_path(resource_name), class: 'login btn btn-warning' %>
        </li>
      </ul>
    <% end -%>
  </div>
</header>

portal_vendors/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal Supplier</title>
    <%= favicon_link_tag 'nutrifood-logo-small.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header', cache: true if ms_vendor_signed_in? %>
    <div class="content content-container">
      <div class="center">
        <% if notice %>
          <p class="alert alert-success alert-dismissible fade in">
            <a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= notice %>
          </p>
        <% elsif alert %>
          <p class="alert alert-danger alert-dismissible fade in">
            <a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= alert %>
          </p>
        <% end -%>
        <% if params[:controller] == 'inquiries' && !@document %>
          <p class="alert alert-danger">
            <a href="javascript:;" class="close" data-dismiss="alert" aria-label="close" onclick="closeErrorMessage();">&times;</a>
             Please upload your "Account Document" <%= link_to 'here', edit_vendor_path(current_ms_vendor, step: 'finance_aspect') %>
          </p>
        <% end %>
        <% if params[:controller] == 'products_and_services' && @flag %>
          <p class="alert alert-danger">
            <a href="javascript:;" class="close" data-dismiss="alert" aria-label="close" onclick="closeErrorMessage();">&times;</a>
             Please upload your service(s) document
          </p>
        <% end %>
      </div>
      <div class="content-container-small">
        <%#= render_breadcrumbs %>
      </div>
    </div>
    <%= yield %>
  </body>
  <footer>
    Copyrights 2019 &copy; iGeeks Tribe All rights reserved.
  </footer>

  <script type="text/javascript">
    function closeErrorMessage(){
      $(".alert").remove();
    }
  </script>
</html>