vendor_management_systems/config/routes.rb
Rails.application.routes.draw do
  resources :tr_rfq_submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete '/logout' => 'vendors#destroy_session'
  get '/unauthorized' => 'authentications#unauthorized'
  resources :worklists do
    member do
      get :decline
      get :verify
      patch :verify_vendor
      patch :decline_vendor
    end
  end

  resources :vendors do
    member do
      get :get_image
    end
  end
  resources :purchasings
  resources :tr_rfqs

  root to: 'worklists#index'
end

vendor_management_systems/app/controllers/worklists_controller.rb
class WorklistsController < ApplicationController
  before_action :set_vendor, only: %i[show verify decline verify_vendor decline_vendor]
  before_action :username, only: %i[verify verify_vendor]
  before_action :generate_password, only: :verify_vendor

  def index
    if params[:office_location].present? || params[:ms_vendor_type_id].present?
      office_location = params[:office_location].downcase rescue nil
      vendor_type = params[:ms_vendor_type_id] rescue nil
      @vendors = MsVendor.search_data(office_location, vendor_type, 1)
    else
      @vendors = MsVendor.where(is_active: 1, vendor_status: 1)
    end
    @ms_vendor_types = MsVendorType.vendor_type_id
    @tr_rfqs = TrRfq.all
    @tr_rfq_submissions = TrRfqSubmission.all
  end

  def show
    @vendor = MsVendor.find(params[:id])
  end

  def verify
    respond_to :js
  end

  def decline
    respond_to :js
  end

  def verify_vendor
    @vendor.assign_attributes(vendor_params)    
    if @vendor.check_username && @vendor.save(validate: false)
      NotificationMailer.verify_vendor(@vendor, @vendor.password).deliver_later
      redirect_to root_url, notice: 'Vendor has been updated.'
    else
      respond_to :js
    end
  end

  def decline_vendor
    @vendor.assign_attributes(vendor_params)
    if @vendor.save(validate: false)
      NotificationMailer.decline_vendor(@vendor).deliver_later
      redirect_to root_url, notice: 'Vendor has been updated.'
    else
      respond_to :js
    end
  end

  private

  def vendor_params
    params.require(:ms_vendor).permit(:username, :password, :reject_reason, :potential_status, :potential_desc, :vendor_status, :created_by, :updated_by)
  end

  def set_vendor
    @vendor = MsVendor.find(params[:id])
  end

  def username
    @username = @vendor.vendor.downcase.remove('pt. ', 'pt ', 'cv. ', 'cv ', ' ').to(7)
  end

  def generate_password
    @vendor.password = SecureRandom.hex(64)[0..10] unless @vendor.encrypted_password?
  end
end

vendor_management_systems/app/helpers/worklists_helper.rb
module WorklistsHelper
end

vendor_management_systems/app/views/worklists/_modal_decline.html.erb
<div class='modal fade' id='modal-decline' role='dialog'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'>&times;</button>
        <h4 class='modal-title'><span class='fa fa-angle-right' aria-hidden='true'></span> Reason of Rejection</h4>
      </div>
      <%= form_for vendor, url: path, html: { class: 'form-horizontal', role: 'form' }, remote: true do |f| %>
        <div class='modal-body'>
          <div class='form-group'>
            <div class='col-sm-3 control-label'>
              <%= f.label :reject_reason, 'Reject Reason' "<font class='font-red'>*</font>".html_safe %>
            </div>
            <div class='col-sm-9'>
              <%= f.text_area :reject_reason, class: 'form-control', required: true %>
              <%= f.hidden_field :vendor_status, value: 3 %>
              <%= f.hidden_field :created_by, value: 1 %>
              <%= f.hidden_field :updated_by, value: 1 %>
            </div>
          </div>
        </div>
        <div class='modal-footer'>
          <%= f.submit 'Submit', class: 'btn btn-warning pull-right', data: { confirm: 'Apakah Anda yakin dengan perubahan ini? ' }  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

vendor_management_systems/app/views/worklists/_modal_verify.html.erb
<div class='modal fade' id='modal-verify' role='dialog'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'>&times;</button>
        <h4 class='modal-title'><span class='fa fa-angle-right' aria-hidden='true'></span> Please Set the Username</h4>
      </div>
      <%= form_for vendor, url: path, html: { class: 'form-horizontal', role: 'form' }, remote: true do |f| %>
        <div class='modal-body'>
          <div class='form-group'>
            <div class='col-sm-3 control-label'>
              <%= f.label :username, 'Username' "<font class='font-red'>*</font>".html_safe %>
            </div>
            <div class='col-sm-9'>
              <%= f.text_field :username, value: f.object.username? ? f.object.username : username, class: 'form-control', required: true %>
            </div>
          </div>
        </div>
        <%= f.hidden_field :vendor_status, value: 2 %>
        <%= f.hidden_field :potential_status, value: true %>
        <%= f.hidden_field :potential_desc, value: 'Potensial' %>
        <%= f.hidden_field :created_by, value: 1 %>
        <%= f.hidden_field :updated_by, value: 1 %>
        <div class='modal-footer'>
          <%= f.submit 'Submit', class: 'btn btn-warning pull-right', data: { confirm: 'Apakah Anda yakin dengan perubahan ini? ' }  %>
        </div>
      <% end -%>
    </div>
  </div>
</div>

vendor_management_systems/app/views/worklists/_rfq_submission.html.erb
<table>
  <thead>
    <tr>
      <th colspan='8' class='title'>RFQ SUBMISSIONS</th>
    </tr>
    <tr>
      <th>RFQ ID</th>
      <th>ITEM NAME</th>
      <th>DESCRIPTION</th>
      <th>QUANTITY</th>
      <th>CREATED DATE</th>
      <th>EXPIRATION DATE</th>
    </tr>
  </thead>
  <tbody>    
    <% @tr_rfq_submissions.each do |rfq_submission| %> 
      <tr>
        <td><%#= rfq_submission.no_rfq %></td> <!-- bapak -->
        <td><%#= rfq_submission.item_name %></td> <!-- bapak -->
        <td><%= rfq_submission.description %></td> 
        <td><%#= rfq_submission.qty %></td> <!-- bapak -->
        <td><%= rfq_submission.created_at %></td> 
        <td><%#= rfq_submission.expiration_date %></td> <!-- bapak -->
      </tr>
    <% end %>
  </tbody>
</table>

vendor_management_systems/app/views/worklists/_rfq_submission2.html.erb
<table>
  <thead>
    <tr>
      <th colspan='8'> 
        <h3 class='btn btn-warning mb' id='min'>
          <span class='fa fa-plus fa-sm' aria-hidden='true'></span> 
          <%= link_to 'Add RFQ', new_tr_rfq_path , class: 'btn btn-warning add-field-button'%>
        </h3>
      </th>
    </tr> 
    <tr>
      <th colspan='8' class='title'>LIST RFQ</th>
    </tr>
    <tr>
      <th>RFQ ID</th>
      <th>ITEM NAME</th>
      <th>DESCRIPTION</th>
      <th>QUANTITY</th>
      <th>CREATED DATE</th>
      <th>EXPIRATION DATE</th>
        <%#= f.link_to_add :ms_vendor_addresses do %>
    </tr>
  </thead>
  <tbody>
    <% @tr_rfqs.each do |rfq| %> 
      <tr>
        <td><%= rfq.no_rfq %></td>
        <td><%= rfq.item_name %></td>
        <td><%= rfq.description %></td>
        <td><%= rfq.qty %></td>
        <td><%= rfq.created_at %></td>
        <td><%= rfq.expiration_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

vendor_management_systems/app/views/worklists/_vendor.html.erb
<div class='form-group' style="margin: 25px auto; width: 90%">
  <%= form_tag worklists_path, method: :get do %>
    <div class='col-sm-12 title'>
      <div class='col-sm-5'>
        <h4><b>VENDORS</b></h4>
      </div>
      <div class='col-sm-3' style="text-align: right;">
        <%= select_tag :ms_vendor_type_id, options_for_select(@ms_vendor_types, params[:ms_vendor_type_id]), prompt: 'Vendor Type', class: 'form-control' %>
      </div>
      <div class='col-sm-3' style="text-align: right;">
        <%= select_tag :office_location, options_for_select(['Indonesia', 'Overseas'], params[:office_location]), prompt: 'Location', class: 'form-control' %>
      </div>
      <div class='col-sm-1'>
        <%= submit_tag 'FILTER', class: 'btn btn-info' %>
      </div>
    </div>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>NO.</th>
      <th>COMPANY NAME</th>
      <th>SALES PHONE</th>
      <th>CITY</th>
      <th>TYPE</th>
      <th>STATUS</th>
      <th colspan='2'>ACTION</th>
    </tr>
  </thead>
  <tbody>
    <% vendors.each.with_index(1) do |vendor, index| %>
      <tr data-link="<%= worklist_url(vendor) %>" class='cursor' >
        <td><%= index %></td>
        <td><%= vendor.vendor %></td>
        <td><%= vendor.sales_phone %></td>
        <td><%= vendor.city %></td>
        <td><%= vendor.ms_vendor_type.type_name rescue 'No Data' %></td>
        <td><%= status_vendor(vendor.vendor_status) %></td>
        <td class='centered not-include'>
          <%= link_to 'VERIFY', verify_worklist_url(vendor), class: 'btn btn-success open-modal', remote: true %>
        </td>
        <td class='centered not-include'>
          <%= link_to 'DECLINE', decline_worklist_url(vendor), class: 'btn btn-danger open-modal', remote: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

vendor_management_systems/app/views/worklists/decline.js.erb
$('.modal-vendor').html('<%= escape_javascript(render partial: 'modal_decline', locals: { vendor: @vendor, path: decline_vendor_worklist_url }) %>');
$('#modal-decline').modal().show();

vendor_management_systems/app/views/worklists/decline_vendor.js.erb
$('.modal-backdrop').remove();
$('.modal-vendor').html('<%= escape_javascript(render partial: 'modal_decline', locals: { vendor: @vendor, path: decline_vendor_worklist_url }) %>');
$('#modal-decline').modal().show();

vendor_management_systems/app/views/worklists/index.html.erb
<div class='row'>
  <%= render 'vendor', vendors: @vendors %>
  <%= render 'rfq_submission2' %>
  <%= render 'rfq_submission' %>
</div>
<div class='modal-vendor'></div>

vendor_management_systems/app/views/worklists/verify.js.erb
$('.modal-vendor').html('<%= escape_javascript(render partial: 'modal_verify', locals: { vendor: @vendor, path: verify_vendor_worklist_url, username: @username }) %>');
$('#modal-verify').modal().show();

vendor_management_systems/app/views/worklists/verify_vendor.js.erb
$('.modal-backdrop').remove();
$('.modal-vendor').html('<%= escape_javascript(render partial: 'modal_verify', locals: { vendor: @vendor, path: verify_vendor_worklist_url, username: @username }) %>');
$('#modal-verify').modal().show();