portal_vendors/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :tr_rfq_submission_dtls
  resources :tr_rfqs
  resources :tr_rfq_submissions
  authenticated :ms_vendor do
    root to: 'inquiries#index', as: :authenticated_root
  end
  root to: redirect('/login')

  devise_for :ms_vendors, path: '', controllers: {
    registrations: 'ms_vendors/registrations', passwords: 'ms_vendors/passwords'
  }, path_names: { sign_in: :login, sign_up: :register, password: :reset, confirmation: :verification }

  namespace :api do
    resources :images, only: :show do
      member do
        get :check_path
        get :get
      end
    end
  end

  resources :vendors do
    member do
      patch :update_password
    end
  end
  resources :inquiries
  resources :products_and_services, only: [:index, :update] do    
    member do
      get :download_template
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

portal_vendors/app/models/tr_rfq.rb
class TrRfq < ApplicationRecord
end

portal_vendors/app/controllers/tr_rfqs_controller.rb
class TrRfqsController < ApplicationController
  before_action :set_tr_rfq, only: [:show, :edit, :update, :destroy]

  # GET /tr_rfqs
  # GET /tr_rfqs.json
  def index
    @tr_rfqs = TrRfq.all
  end

  # GET /tr_rfqs/1
  # GET /tr_rfqs/1.json
  def show
  end

  # GET /tr_rfqs/new
  def new
    @tr_rfq = TrRfq.new
  end

  # GET /tr_rfqs/1/edit
  def edit
  end

  # POST /tr_rfqs
  # POST /tr_rfqs.json
  def create
    @tr_rfq = TrRfq.new(tr_rfq_params)

    respond_to do |format|
      if @tr_rfq.save
        format.html { redirect_to @tr_rfq, notice: 'Tr rfq was successfully created.' }
        format.json { render :show, status: :created, location: @tr_rfq }
      else
        format.html { render :new }
        format.json { render json: @tr_rfq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tr_rfqs/1
  # PATCH/PUT /tr_rfqs/1.json
  def update
    respond_to do |format|
      if @tr_rfq.update(tr_rfq_params)
        format.html { redirect_to @tr_rfq, notice: 'Tr rfq was successfully updated.' }
        format.json { render :show, status: :ok, location: @tr_rfq }
      else
        format.html { render :edit }
        format.json { render json: @tr_rfq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tr_rfqs/1
  # DELETE /tr_rfqs/1.json
  def destroy
    @tr_rfq.destroy
    respond_to do |format|
      format.html { redirect_to tr_rfqs_url, notice: 'Tr rfq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tr_rfq
      @tr_rfq = TrRfq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tr_rfq_params
      params.require(:tr_rfq).permit(:item_name, :ms_vendor_type_id, :delivery_sie, :note, :description, :need_by_date, :term_of_payment, :is_active, :created_by, :updated_by, :status, :expiration_date, :qty, :uom, :no_rfq)
    end
end

portal_vendors/app/helpers/tr_rfqs_helper.rb
module TrRfqsHelper
end

portal_vendors/app/views/tr_rfqs/_form.html.erb
<%= form_with(model: tr_rfq, local: true) do |form| %>
  <% if tr_rfq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tr_rfq.errors.count, "error") %> prohibited this tr_rfq from being saved:</h2>

      <ul>
      <% tr_rfq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_area :item_name %>
  </div>

  <div class="field">
    <%= form.label :ms_vendor_type_id %>
    <%= form.number_field :ms_vendor_type_id %>
  </div>

  <div class="field">
    <%= form.label :delivery_sie %>
    <%= form.text_area :delivery_sie %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :need_by_date %>
    <%= form.date_select :need_by_date %>
  </div>

  <div class="field">
    <%= form.label :term_of_payment %>
    <%= form.number_field :term_of_payment %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.check_box :is_active %>
  </div>

  <div class="field">
    <%= form.label :created_by %>
    <%= form.number_field :created_by %>
  </div>

  <div class="field">
    <%= form.label :updated_by %>
    <%= form.number_field :updated_by %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= form.label :qty %>
    <%= form.number_field :qty %>
  </div>

  <div class="field">
    <%= form.label :uom %>
    <%= form.text_field :uom %>
  </div>

  <div class="field">
    <%= form.label :no_rfq %>
    <%= form.text_field :no_rfq %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

portal_vendors/app/views/tr_rfqs/edit.html.erb
<h1>Editing Tr Rfq</h1>

<%= render 'form', tr_rfq: @tr_rfq %>

<%= link_to 'Show', @tr_rfq %> |
<%= link_to 'Back', tr_rfqs_path %>

portal_vendors/app/views/tr_rfqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tr Rfqs</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Ms vendor type</th>
      <th>Delivery sie</th>
      <th>Note</th>
      <th>Description</th>
      <th>Need by date</th>
      <th>Term of payment</th>
      <th>Is active</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th>Status</th>
      <th>Expiration date</th>
      <th>Qty</th>
      <th>Uom</th>
      <th>No rfq</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tr_rfqs.each do |tr_rfq| %>
      <tr>
        <td><%= tr_rfq.item_name %></td>
        <td><%= tr_rfq.ms_vendor_type_id %></td>
        <td><%= tr_rfq.delivery_sie %></td>
        <td><%= tr_rfq.note %></td>
        <td><%= tr_rfq.description %></td>
        <td><%= tr_rfq.need_by_date %></td>
        <td><%= tr_rfq.term_of_payment %></td>
        <td><%= tr_rfq.is_active %></td>
        <td><%= tr_rfq.created_by %></td>
        <td><%= tr_rfq.updated_by %></td>
        <td><%= tr_rfq.status %></td>
        <td><%= tr_rfq.expiration_date %></td>
        <td><%= tr_rfq.qty %></td>
        <td><%= tr_rfq.uom %></td>
        <td><%= tr_rfq.no_rfq %></td>
        <td><%= link_to 'Show', tr_rfq %></td>
        <td><%= link_to 'Edit', edit_tr_rfq_path(tr_rfq) %></td>
        <td><%= link_to 'Destroy', tr_rfq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tr Rfq', new_tr_rfq_path %>

portal_vendors/app/views/tr_rfqs/new.html.erb
<h1>New Tr Rfq</h1>

<%= render 'form', tr_rfq: @tr_rfq %>

<%= link_to 'Back', tr_rfqs_path %>

portal_vendors/app/views/tr_rfqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @tr_rfq.item_name %>
</p>

<p>
  <strong>Ms vendor type:</strong>
  <%= @tr_rfq.ms_vendor_type_id %>
</p>

<p>
  <strong>Delivery sie:</strong>
  <%= @tr_rfq.delivery_sie %>
</p>

<p>
  <strong>Note:</strong>
  <%= @tr_rfq.note %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tr_rfq.description %>
</p>

<p>
  <strong>Need by date:</strong>
  <%= @tr_rfq.need_by_date %>
</p>

<p>
  <strong>Term of payment:</strong>
  <%= @tr_rfq.term_of_payment %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @tr_rfq.is_active %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @tr_rfq.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @tr_rfq.updated_by %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tr_rfq.status %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @tr_rfq.expiration_date %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @tr_rfq.qty %>
</p>

<p>
  <strong>Uom:</strong>
  <%= @tr_rfq.uom %>
</p>

<p>
  <strong>No rfq:</strong>
  <%= @tr_rfq.no_rfq %>
</p>

<%= link_to 'Edit', edit_tr_rfq_path(@tr_rfq) %> |
<%= link_to 'Back', tr_rfqs_path %>